# Generated by Django 4.1.7 on 2023-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.DeleteModel(
            name='AccountModel',
        ),
    ]
