# Generated by Django 4.1.7 on 2023-06-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_userdata_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='mname',
            new_name='middle_name',
        ),
    ]
