# Generated by Django 4.1.7 on 2023-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_customuser_uid_delete_accountmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('bday', models.DateField()),
                ('year', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
            ],
        ),
    ]
