# Generated by Django 4.1.7 on 2023-05-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='student_number',
            field=models.CharField(default='', max_length=8),
        ),
    ]
