# Generated by Django 4.1.7 on 2023-05-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_userdata_student_number'),
    ]

    operations = [
    ]
