# Generated by Django 4.1.7 on 2023-05-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_auto_20230504_0947'),
    ]

    operations = [
    migrations.RemoveField(
    model_name='UserData', # Replace 'user_data' with the actual name of the model
    name='bday',
),
    ]
