# Generated by Django 4.1.7 on 2023-05-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_auto_20230504_0950'),
    ]

    operations = [
    ]
